### ISSUE TITLE
Letter colour blocks

### ISSUE THREAD

**Issue by EdricChan03** [Chan4077/First-Mod#7]
In the 1.11.2 version of my mod, there was a basic implementation of letter colour blocks, although it involved a lot of code just for all the 26 letters of the block.

# Todos:
- [ ] Add basic implementation of letter colour blocks (`BlockVariant`?)
- [ ] Add different colour customizations
- [ ] Add a GUI helper to customize the letter for a small price of an iron ingot, gold ingot, diamond or emerald (See #9)
- [ ] Consider the price of an actual block

# Questions to consider:
- Make the block uncraftable?
